### ISSUE TITLE
cannot fetch because of CORS origin header error

### ISSUE THREAD

**Issue by VISHWAJ33T** [mohd-baquir-qureshi/music-api#1]
cannot fetch your api because of some CORS origin in your api header

**Comment by mohd-baquir-qureshi** [comment]
Added the "Access-Control-Allow-Origin" header value to "*", now can try again.

**Comment by mohd-baquir-qureshi** [comment]
Added the "Access-Control-Allow-Origin" header value to "*", now you can try again.

**Comment by VISHWAJ33T** [comment]
its working now.thanks!
