### ISSUE TITLE
seevn is broken

### ISSUE THREAD

**Issue by adi8ya** [mohd-baquir-qureshi/music-api#3]
seevn is broken all i get in any response is

curl "https://musicapi.x007.workers.dev/search?q=shivoham&searchEngine=seevn"
{"status":200,"response":[],"message":"success"}
curl "https://musicapi.x007.workers.dev/search?q=tumkyamile&searchEngine=seevn"
{"status":200,"response":[],"message":"success"}

**Comment by mohd-baquir-qureshi** [comment]
Fixed
