### ISSUE TITLE
Nice api one issue is please Provide original url

### ISSUE THREAD

**Issue by anirudhanishal** [mohd-baquir-qureshi/music-api#5]
Nice api one issue is please Provide original url
Like gaana, Hungama provide various quality of images and songs

**Comment by mohd-baquir-qureshi** [comment]
Thanks

Sorry can't provide original URLs. its encrypted for security reason.

**Comment by anirudhanishal** [comment]
Ok no problem

**Comment by anirudhanishal** [comment]
Can I enter link to download songs with cover

**Comment by mohd-baquir-qureshi** [comment]
No its not supported.
